export const commons = {
	title: 'عنوان',
	options: 'گزینه ها',
	search: 'جستجو',
	submit: 'ثبت',
	reset: 'بازنشانی',
	notifications: 'اطلاعیه ها',
	exit: 'خروج',
	show_all: 'نمایش همه',
	add: 'افزودن',
	is_active: 'فعال',
	is_started: 'شروع شده',
	not_found: 'موردی یافت نشد.',
	enable: 'فعال',
	disable: 'غیرفعال',
	connection_error: 'خطا در ارتباط با سرور',
	invalid_confirm_password: 'عدم تطابق رمز های عبور جدید',
	change_password: 'ویرایش رمز عبور',
	success_new_pass: 'رمز عبور با موفقیت تغییر یافت.',
	email: 'ایمیل',
	dashboard_start: 'از اینجا شروع کنید',
	password_equality: 'از یکی بودن رمز های عبور مطمئن شوید',
	receive_data: 'دریافت اطلاعات',
	excel_download: 'دریافت فایل اکسل'
};
