export const user = {
	user: 'کاربر',
	username: 'نام کاربری',
	national_code: 'کد ملی',
	full_name: 'نام و نام حانوادگی',
	user_dt_title: 'کاربران',
	user_upsert_header: 'اطلاعات کاربر',
	user_account_info: 'اطلاعات حساب کاربری',
	roles: 'نقش ها',
	user_personal_info: 'اطلاعات هویتی',
	name: 'نام',
	family: 'نام خانوادگی',
	father_name: 'نام پدر',
	user_teaching_info: 'اطلاعات مدرسی',
	teaching_code: 'کد مدرسی',
	start_semester: 'نیمسال ورود',
	education_degree: 'مدرک تحصیلی',
	score: 'امتیاز',
	user_course_field_dt_title: 'دروس',
	user_field_group_dt_title: 'گروه های درسی',
	professor: 'استاد'
}
